### ISSUE TITLE
Two different requests with same API call

### ISSUE THREAD

**Issue by atbenedict** [artportfolio/Back-End-Architect#6]
The Readme.md has two requests:

1. get a user profile with all post

method url: /api/users/posts/:id (id meaning id of the user)

2. get All post from user, without user info

method url: /api/users/posts/:id (id meaning id of the user) 

Which one is which?

**Comment by BrooksPoltl** [comment]
My bad I'll adjust the documentation

**Comment by atbenedict** [comment]
No prob - you're killing it!
